### PR TITLE
fix the direct call of App::CLI->app; fix help command caused by the changes of "->app returns object"

### PR DESCRIPTION
**Pull request by sunnavy**
both are small changes, and I assume the patches are quite straightforward ;)

### CODE REVIEW

**Comment by paultcochrane** [comment]
You're right, both patches are quite straightforward :-)

What lead you to this bug?  Is there a downstream package no longer working as a result?  If so, which one(s)?  I'm a new maintainer of the module, so such feedback is vital so that when I update the code I don't break anything downstream.  Also, have you got a test demonstrating the correct/expected behaviour?

Thanks heaps for your patch!!

**Comment by sunnavy** [comment]
Well, one of my module "Shipwright" depends on it and it's broken badly by the new behavior :)
I tested with Shipwright and it works fine with the patches, sorry that I didn't write test cases for the patches themselves.

Thanks for the quick response :)

**Comment by paultcochrane** [comment]
Thanks for the quick feedback!  That's good to know that your package depends upon it.  I tried increasing the test coverage to at least document current behaviour, but there are still corners that I've missed.  My apologies for causing breakages to your package!  I'll get an updated version out as soon as I can.

**Comment by sunnavy** [comment]
Great and thank you!

Regards
sunnavy

**Comment by paultcochrane** [comment]
Merged in d9eb264.  I've added more tests so that the current behaviour is better documented.  Version 0.48 should be hitting CPAN soon.  Many thanks for pointing this issue out to me and for the patches :-)

**Pull request merged**
